# This file defines the content types on the website. See the documentation for
# details: https://docs.bolt.cm/contenttypes/intro

# The Homepage content type is a singleton: There can be only one record of this
# content type.

homepage:
    name: Homepage
    singular_name: Homepage
    fields:
        title:
            type: text
            class: large
            localize: true
            label: Title
        sub:
            label: Sub
            type: text
            localize: true
                
        background_image:
            type: image
            label: Background image

        image_ayn:
            type: image
            label: Image Ayn

        who_is:
            label: Who is
            type: collection
            limit: 3
            fields:
                button:
                    label: Button
                    type: set
                    fields:
                        button_text:
                            label: Button text
                            type: text
                            localize: true
                        colorvalue:
                            label: alternative color
                            type: select
                            values: { 'blue': "blue" }
                        link:
                            label: Link
                            type: text

        quote:
            type: text
            localize: true
            display:

        conent1:
            label: Content
            type: redactor
            localize: true

        imagebox:
            label: Image box
            type: collection
            fields:
                image_en_text:
                    label: image en text
                    type: set
                    fields:
                        head:
                            label: Head
                            type: text
                            localize: true
                        image:
                            label: Image
                            type: image
                            localize: false
                        subtext:
                            label: Sub text
                            type: text
                            localize: true
                        link: 
                            label: Link
                            type: text
                            localize: true
        
        conent2:
            label: Content
            type: redactor
            localize: true

    viewless: false
    taxonomy: [ categories, tags, foobars ]
    locales: ['en', 'nl']
    singleton: true
    icon_many: "fa:home"
    icon_one: "fa:home"


# Pages can be used for the more 'static' pages on your site. This content-type
# has a 'templateselect' field, which allows you to override the record_template
# setting for an individual page.
# The taxonomy for this ContentType is defined as 'groups', which is a so-called
# "grouping taxonomy". This way you can easily group sets of pages that logically
# belong together. If your site has a 'services' section, in which you'd like to
# list the different types of services a company provides, you can group these
# together.

pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            label: Title
            type: text
            class: large
            localize: true
    
        quote:
            label: Quote
            type: text
            localize: true

        list_items:
            label: List items
            type: collection
            fields:
                items:
                    label: items
                    type: set
                    fields:
                        list_text:
                            label: Text
                            type: text
                            localize: true
                        link:
                            label: Video URL
                            type: link
                        tooltip:
                            label: Tooltip
                            type: redactor
                            localize: true
            
        slug:
            type: slug
            uses: [ title ]
            group: Meta

    taxonomy: [ groups ]
    locales: ['en', 'nl']
    records_per_page: 5
    order: id


# Entries can be used for things like 'news' or 'blogpostings'. They have a
# 'teaser', which can be used for a short blurb on listing-pages, allowing
# visitors to click-through to the rest of the entry. It also has fields for an
# image and an optional video embed.
# A relation is defined to the pages ContentType. This way you can refer to a
# page from your news-item.
# This ContentType defines 'categories' and 'tags' as taxonomies, allowing the
# editor to use both to categorize a specific entry.
# The 'order' is set to '-datepublish', which means that newer entries will be
# shown above older entries.

contact:
    name: contact
    singular_name: contact
    fields:
        title:
            label: title
            type: text
            class: large
            localize: true

        name:
            label: name
            type: text

        photo:
            label: Photo
            type: image

        email:
            label: Email
            type: email
 
        slug:
            type: slug
            uses: [ title ]
            group: Meta
    
    record_template: contact.twig
    taxonomy: [ groups ]
    locales: ['en', 'nl']
    records_per_page: 5

