# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/menus

main:
  - label: Home
    link: homepage
  - label: Man
    link: /page/man
  - label: Philosophy
    link: Philosophy
  - label: Issues
    link: Issues
  - label: Applications
    link: Applications

foo: header
