# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/menus

en:
  - label: Home
    link: /en/homepage
  - label: Man
    link: /en/page/man
  - label: Philosophy
    link: /en/page/philosophy
  - label: Issues
    link: /en/page/issues
  - label: Applications
    link: /en/page/applications

nl:
  - label: Home
    link: /nl/homepage
  - label: Mens
    link: /nl/page/man
  - label: Filosofie
    link: /nl/page/philosophy
  - label: Kwesties
    link: /nl/page/issues
  - label: Toepassingen
    link: /nl/page/applications